[project]
name = "random-anime"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "colorama>=0.4.6",
    "lxml>=6.0.0",
    "requests>=2.32.4",
]
